[project]
name = "ignis"
description = "Machine learning models for doing interesting things related to Yu-Gi-Oh!"
readme = "README.md"
authors = [{name = "Sup#2.0"}]
# license = {file = "LICENSE"}
requires-python = ">= 3.10"
dependencies = [
  "requests",
  "tensorflow",
]
keywords = []
