name: Ai-bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ''

    steps:
      - name: 'Git – checkout'
        uses: actions/checkout@v4
  
      - name: 'Python – setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: 'Python – install packages'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: 'Python – execute'
        env:
          LINK: ${{ secrets.LINK }}
        run: python disc/__main__.py
