name: Ai-bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'

    steps:
      - name: 'Git – set working directory'
        run: echo "$HOME" >> $GITHUB_PATH
        
      - name: 'Git – checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: 'Git – checkout suptools'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: Sup2point0/suptools
      #     path: suptools
  
      - name: 'Python – setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: 'Python – install packages'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: 'Python – execute'
        env:
          LINK: ${{ secrets.LINK }}
        # run: python disc/__main__.py
        run: cd disc && python __main__.py
